services:
  pmicgen-jupyter:
    image: ghcr.io/pmicgen/pmicgen:latest
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    ports:
      - '8888:8888'
    environment:
      - GRANT_SUDO=yes
